version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app
    ports:
      - "${APP_PORT}:3000"
      - "9229:9229"
    command: npm run start:debug
  mongodb:
    image: mongo:${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local