version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app
    ports:
      - "${APP_PORT}:3000"
      - "9229:9229"
    command: npm run start:debug